apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskspace
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: taskspace.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: taskspace-backend
                port:
                  number: 3000
          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: taskspace-backend
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taskspace-frontend
                port:
                  number: 80
